<a href="https://colab.research.google.com/github/KIMJUNHO-kmou/-/blob/main/4%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#문제 9

In [2]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/air_quality.csv")

In [3]:
# 1) IQR 계산
Q1 = df['CO2'].quantile(0.25)
Q3 = df['CO2'].quantile(0.75)
IQR = Q3 -Q1
print(Q1, Q3, IQR)

383.8502072254157 418.7784333384595 34.92822611304376

In [4]:
# 2) 상한및하한계산
upper = Q3 + 1.5 * IQR
lower = Q1 -1.5 * IQR
print(upper, lower)

471.17077250802515 331.4578680558501

In [5]:
# 3) 이상치식별
outliers = df[(df['CO2'] < lower) | (df['CO2'] > upper)]
print(outliers)

                     Date        CO         CO2         O2
88    2024-01-04 16:00:00  0.447024  603.471090  20.712496
155   2024-01-07 11:00:00  0.428565  588.211313  22.013521
185   2024-01-08 17:00:00  0.571400  472.852730  21.667225
196   2024-01-09 04:00:00  0.411614  607.631613  21.072704
228   2024-01-10 12:00:00  0.428470  595.429242  20.319365
...                   ...       ...         ...        ...
9908  2025-02-16 20:00:00  0.606182  595.889840  21.572550
9938  2025-02-18 02:00:00  0.373704  627.451289  20.840325
9953  2025-02-18 17:00:00  0.403922  639.521653  19.060725
9962  2025-02-19 02:00:00  0.568850  328.099193  21.601589
9966  2025-02-19 06:00:00  0.451337  646.129551  20.328131

[304 rows x 4 columns]

In [6]:
# 4) 이상치수
print(len(outliers))

304

In [ ]:
#문제 10

In [8]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/drinks.csv")

In [9]:
# 1) 대륙별맥주소비량의평균
continent = df.groupby("continent")['beer_servings'].mean()
print(continent)

continent
Africa            61.471698
Asia              37.045455
Europe           193.777778
North America    145.434783
Oceania           89.687500
South America    175.083333
Name: beer_servings, dtype: float64

In [10]:
top_continent = continent.idxmax()
print(top_continent)

Europe

In [11]:
# 2) 국가별맥주소비량
cond = df['continent'] == top_continent
df = df[cond]
df

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
1,Albania,89,132,54,4.9,Europe
3,Andorra,245,138,312,12.4,Europe
7,Armenia,21,179,11,3.8,Europe
9,Austria,279,75,191,9.7,Europe
10,Azerbaijan,21,46,5,1.3,Europe
15,Belarus,142,373,42,14.4,Europe
16,Belgium,295,84,212,10.5,Europe
21,Bosnia-Herzegovina,76,173,8,4.6,Europe
25,Bulgaria,231,252,94,10.3,Europe
42,Croatia,230,87,254,10.2,Europe
44,Cyprus,192,154,113,8.2,Europe
45,Czech Republic,361,170,134,11.8,Europe
48,Denmark,224,81,278,10.4,Europe
57,Estonia,224,194,59,9.5,Europe
60,Finland,263,133,97,10.0,Europe
61,France,127,151,370,11.8,Europe
64,Georgia,52,100,149,5.4,Europe
65,Germany,346,117,175,11.3,Europe
67,Greece,133,112,218,8.3,Europe
75,Hungary,234,215,185,11.3,Europe
76,Iceland,233,61,78,6.6,Europe
81,Ireland,313,118,165,11.4,Europe
83,Italy,85,42,237,6.5,Europe
93,Latvia,281,216,62,10.5,Europe
98,Lithuania,343,244,56,12.9,Europe
99,Luxembourg,236,133,271,11.4,Europe
105,Malta,149,100,120,6.6,Europe
111,Monaco,0,0,0,0.0,Europe
113,Montenegro,31,114,128,4.9,Europe
120,Netherlands,251,88,190,9.4,Europe
126,Norway,169,71,129,6.7,Europe
135,Poland,343,215,56,10.9,Europe
136,Portugal,194,67,339,11.0,Europe
139,Moldova,109,226,18,6.3,Europe
140,Romania,297,122,167,10.4,Europe
147,San Marino,0,0,0,0.0,Europe
151,Serbia,283,131,127,9.6,Europe
155,Slovakia,196,293,116,11.4,Europe
156,Slovenia,270,51,276,10.6,Europe
160,Spain,284,157,112,10.0,Europe
165,Sweden,152,60,186,7.2,Europe
166,Switzerland,185,100,280,10.2,Europe
170,Macedonia,106,27,86,3.9,Europe
180,Ukraine,206,237,45,8.9,Europe
182,United Kingdom,219,126,195,10.4,Europe

In [12]:
df = df.sort_values('beer_servings', ascending=False)
df

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
45,Czech Republic,361,170,134,11.8,Europe
65,Germany,346,117,175,11.3,Europe
98,Lithuania,343,244,56,12.9,Europe
135,Poland,343,215,56,10.9,Europe
81,Ireland,313,118,165,11.4,Europe
140,Romania,297,122,167,10.4,Europe
16,Belgium,295,84,212,10.5,Europe
160,Spain,284,157,112,10.0,Europe
151,Serbia,283,131,127,9.6,Europe
93,Latvia,281,216,62,10.5,Europe
9,Austria,279,75,191,9.7,Europe
156,Slovenia,270,51,276,10.6,Europe
60,Finland,263,133,97,10.0,Europe
120,Netherlands,251,88,190,9.4,Europe
3,Andorra,245,138,312,12.4,Europe
99,Luxembourg,236,133,271,11.4,Europe
75,Hungary,234,215,185,11.3,Europe
76,Iceland,233,61,78,6.6,Europe
25,Bulgaria,231,252,94,10.3,Europe
42,Croatia,230,87,254,10.2,Europe
48,Denmark,224,81,278,10.4,Europe
57,Estonia,224,194,59,9.5,Europe
182,United Kingdom,219,126,195,10.4,Europe
180,Ukraine,206,237,45,8.9,Europe
155,Slovakia,196,293,116,11.4,Europe
136,Portugal,194,67,339,11.0,Europe
44,Cyprus,192,154,113,8.2,Europe
166,Switzerland,185,100,280,10.2,Europe
126,Norway,169,71,129,6.7,Europe
165,Sweden,152,60,186,7.2,Europe
105,Malta,149,100,120,6.6,Europe
15,Belarus,142,373,42,14.4,Europe
67,Greece,133,112,218,8.3,Europe
61,France,127,151,370,11.8,Europe
139,Moldova,109,226,18,6.3,Europe
170,Macedonia,106,27,86,3.9,Europe
1,Albania,89,132,54,4.9,Europe
83,Italy,85,42,237,6.5,Europe
21,Bosnia-Herzegovina,76,173,8,4.6,Europe
64,Georgia,52,100,149,5.4,Europe
113,Montenegro,31,114,128,4.9,Europe
7,Armenia,21,179,11,3.8,Europe
10,Azerbaijan,21,46,5,1.3,Europe
111,Monaco,0,0,0,0.0,Europe
147,San Marino,0,0,0,0.0,Europe

In [13]:
df.iloc[4, 1] # 또는 df.iloc[4]['beer_servings']

np.int64(313)

In [ ]:
#문제 11-1

In [16]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/tourist.csv")

In [17]:
# 1) 방문객합계및관광객비율계산
df['방문객합계'] = df['관광'] + df['공무'] + df['사업'] + df['기타']
df['관광객비율'] = df['관광'] / df['방문객합계']
df

       나라    관광   공무   사업   기타  방문객합계     관광객비율
0     국가1  1184  270  380   55   1889  0.626787
1     국가2  1059  184  267   86   1596  0.663534
2     국가3  1129  168  261   50   1608  0.702114
3     국가4   692  106  214  125   1137  0.608619
4     국가5  1335  296  296   84   2011  0.663849
..    ...   ...  ...  ...  ...    ...       ...
95   국가96   898  119  244  132   1393  0.644652
96   국가97  1111  195  234  118   1658  0.670084
97   국가98  1065  172  362   72   1671  0.637343
98   국가99  1408  254  288  149   2099  0.670796
99  국가100  1133  294  233  133   1793  0.631902

[100 rows x 7 columns]

In [18]:
# 2) 조건에맞는값찾기
a = df.sort_values('관광객비율', ascending=False).iloc[1, 3]
b = df.sort_values('관광', ascending=False).iloc[1, 2]
print(a+b)

441

In [ ]:
#문제 11-2

In [19]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/tourist.csv")

In [20]:
df['방문객합계'] = df['관광'] + df['공무'] + df['사업'] + df['기타']
df['관광객비율'] = df['관광'] / df['방문객합계']

In [23]:
# 2) 조건에맞는값찾기
a = df.nlargest(2, '관광객비율').iloc[1]['사업']  #n번째 큰값
b = df.nlargest(2, '관광').iloc[1]['공무']
print(a+b)

441

In [ ]:
#문제 12-1

In [25]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/chem.csv")

In [26]:
# 1) Min-Max 스케일링(데이터프레임으로만들기)
scaler = MinMaxScaler()
df['co_scaled'] = scaler.fit_transform(df[['co']])
df['nmhc_scaled'] = scaler.fit_transform(df[['nmhc']])
df

   sample   co  nmhc  etc  co_scaled  nmhc_scaled
0     샘플1   79    54   31   0.680851     0.500000
1     샘플2   84    57   58   0.734043     0.534091
2     샘플3  109    74  113   1.000000     0.727273
3     샘플4   15    77   21   0.000000     0.761364
4     샘플5   65    77  115   0.531915     0.761364
..    ...  ...   ...  ...        ...          ...
95   샘플96   56    58   86   0.436170     0.545455
96   샘플97   33    59  111   0.191489     0.556818
97   샘플98   55    79  105   0.425532     0.784091
98   샘플99   69    51   59   0.574468     0.465909
99  샘플100   94    45   59   0.840426     0.397727

[100 rows x 6 columns]

In [27]:
# 2) 표준편차계산(판다스표준편차)
co_std = df['co_scaled'].std()
nmhc_std = df['nmhc_scaled'].std()
print(co_std, nmhc_std)

0.2856516497116944 0.3030617020578397

In [28]:
# 3) 표준편차차이계산및반올림
std_diff = round(co_std - nmhc_std, 3)
print(std_diff)

-0.017

In [ ]:
#문제 12-2

In [29]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/chem.csv")

In [31]:
# 1) Min-Max 스케일링 (transform의 결과는 넘파이)
scaler = MinMaxScaler()
co_scaled = scaler.fit_transform(df[['co']])
nmhc_scaled = scaler.fit_transform(df[['nmhc']])
co_scaled

array([[0.68085106],
       [0.73404255],
       [1.        ],
       [0.        ],
       [0.53191489],
       [0.38297872],
       [0.36170213],
       [0.5106383 ],
       [0.9893617 ],
       [0.03191489],
       [0.44680851],
       [0.81914894],
       [0.22340426],
       [0.77659574],
       [0.        ],
       [0.10638298],
       [0.45744681],
       [0.61702128],
       [0.24468085],
       [0.62765957],
       [0.0212766 ],
       [0.65957447],
       [0.37234043],
       [1.        ],
       [0.71276596],
       [0.87234043],
       [0.4893617 ],
       [0.21276596],
       [0.86170213],
       [0.53191489],
       [0.28723404],
       [0.14893617],
       [0.43617021],
       [0.61702128],
       [0.69148936],
       [0.38297872],
       [0.10638298],
       [0.91489362],
       [0.45744681],
       [0.11702128],
       [0.0212766 ],
       [0.54255319],
       [0.85106383],
       [0.34042553],
       [0.57446809],
       [0.        ],
       [0.40425532],
       [0.20212766],
       [0.4893617 ],
       [0.44680851],
       [0.59574468],
       [0.63829787],
       [0.81914894],
       [0.31914894],
       [0.25531915],
       [0.0212766 ],
       [0.03191489],
       [1.        ],
       [0.13829787],
       [0.42553191],
       [0.76595745],
       [0.20212766],
       [0.76595745],
       [0.27659574],
       [0.70212766],
       [0.55319149],
       [0.71276596],
       [0.64893617],
       [0.14893617],
       [0.04255319],
       [0.71276596],
       [0.11702128],
       [0.91489362],
       [0.81914894],
       [0.79787234],
       [0.59574468],
       [0.17021277],
       [0.25531915],
       [0.30851064],
       [0.22340426],
       [0.26595745],
       [0.85106383],
       [0.63829787],
       [0.64893617],
       [0.88297872],
       [0.35106383],
       [0.34042553],
       [0.74468085],
       [0.90425532],
       [0.32978723],
       [0.13829787],
       [0.75531915],
       [0.59574468],
       [0.25531915],
       [0.84042553],
       [0.43617021],
       [0.19148936],
       [0.42553191],
       [0.57446809],
       [0.84042553]])

In [32]:
nmhc_scaled

array([[0.5       ],
       [0.53409091],
       [0.72727273],
       [0.76136364],
       [0.76136364],
       [0.10227273],
       [0.94318182],
       [0.23863636],
       [0.40909091],
       [0.98863636],
       [0.79545455],
       [1.        ],
       [1.        ],
       [0.13636364],
       [0.65909091],
       [0.73863636],
       [0.44318182],
       [0.98863636],
       [0.52272727],
       [1.        ],
       [0.92045455],
       [0.42045455],
       [0.28409091],
       [0.875     ],
       [0.81818182],
       [0.10227273],
       [0.22727273],
       [0.90909091],
       [0.78409091],
       [0.89772727],
       [0.53409091],
       [0.72727273],
       [0.93181818],
       [1.        ],
       [0.55681818],
       [0.32954545],
       [0.21590909],
       [0.21590909],
       [0.15909091],
       [0.44318182],
       [0.36363636],
       [0.73863636],
       [0.10227273],
       [0.64772727],
       [0.36363636],
       [0.35227273],
       [0.84090909],
       [0.26136364],
       [0.39772727],
       [0.85227273],
       [0.625     ],
       [0.31818182],
       [0.38636364],
       [0.        ],
       [0.        ],
       [0.40909091],
       [0.60227273],
       [0.05681818],
       [0.43181818],
       [0.19318182],
       [0.89772727],
       [0.04545455],
       [0.47727273],
       [0.65909091],
       [0.35227273],
       [0.01136364],
       [0.73863636],
       [0.46590909],
       [0.64772727],
       [0.39772727],
       [0.125     ],
       [0.52272727],
       [0.93181818],
       [0.        ],
       [0.15909091],
       [0.60227273],
       [0.13636364],
       [0.47727273],
       [0.95454545],
       [0.85227273],
       [0.77272727],
       [0.06818182],
       [0.77272727],
       [0.53409091],
       [0.03409091],
       [0.86363636],
       [0.59090909],
       [0.88636364],
       [0.17045455],
       [0.22727273],
       [0.65909091],
       [0.26136364],
       [0.89772727],
       [0.14772727],
       [0.96590909],
       [0.54545455],
       [0.55681818],
       [0.78409091],
       [0.46590909],
       [0.39772727]])

In [34]:
# 2) 표준편차계산(넘파이표준편차)
co_std = co_scaled.std()
nmhc_std = nmhc_scaled.std()
print(co_std, nmhc_std)

0.2842198028519168 0.3015425862157

In [35]:
# 3) 표준편차차이계산및반올림
std_diff = round(co_std - nmhc_std, 3)
print(std_diff)

-0.017

In [ ]:
#문제 13-1

In [39]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/loan.csv")

In [42]:
# 1) 총대출액컬럼생성
df['총대출액'] = df['신용대출'] + df['담보대출']
df

            지역코드  성별    신용대출     담보대출     총대출액
0     4100000000   1  688608  5706058  6394666
1     4100000000   2  611035  2260521  2871556
2     4100000001   1  125392  5946493  6071885
3     4100000001   2  239679  4711962  4951641
4     4100000002   1  623758  5411745  6035503
...          ...  ..     ...      ...      ...
4995  4100000511   1  104176  8757588  8861764
4996  4100000157   2  321815  6782991  7104806
4997  4100000309   2  519114  6318150  6837264
4998  4100000341   1  106840  4103058  4209898
4999  4100000577   1  618898  7612392  8231290

[5000 rows x 5 columns]

In [43]:
df.groupby(['지역코드', '성별'])['총대출액'].sum()

지역코드        성별
4100000000  1     22891981
            2     18339609
4100000001  1     34197683
            2     17595557
4100000002  1     13119017
                    ...
4100000589  2     17797635
4100000590  1     16813363
            2     23655928
4100000591  1     20674327
            2     12204772
Name: 총대출액, Length: 1184, dtype: int64

In [46]:
# 2) 지역코드와성별별로총대출액합계계산
grouped = df.groupby(['지역코드', '성별'])['총대출액'].sum().unstack()
grouped

성별                 1         2
지역코드
4100000000  22891981  18339609
4100000001  34197683  17595557
4100000002  13119017  21827691
4100000003  16549091  54654134
4100000004  26831399  56145359
...              ...       ...
4100000587   9050332  19445103
4100000588  47396699  36281031
4100000589  28256320  17797635
4100000590  16813363  23655928
4100000591  20674327  12204772

[592 rows x 2 columns]

In [47]:
# 3) 성별 간총대출액차이가가장큰지역코드찾기(절대값 사용)
grouped['차이'] = abs(grouped[1] - grouped[2])
result = grouped['차이'].idxmax()
print(result)

4100000278

In [ ]:
#문제 13-2

In [48]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/loan.csv")

In [49]:
# 1) 총대출액컬럼생성
df['총대출액'] = df['신용대출'] + df['담보대출']
df

            지역코드  성별    신용대출     담보대출     총대출액
0     4100000000   1  688608  5706058  6394666
1     4100000000   2  611035  2260521  2871556
2     4100000001   1  125392  5946493  6071885
3     4100000001   2  239679  4711962  4951641
4     4100000002   1  623758  5411745  6035503
...          ...  ..     ...      ...      ...
4995  4100000511   1  104176  8757588  8861764
4996  4100000157   2  321815  6782991  7104806
4997  4100000309   2  519114  6318150  6837264
4998  4100000341   1  106840  4103058  4209898
4999  4100000577   1  618898  7612392  8231290

[5000 rows x 5 columns]

In [51]:
# 2) 지역코드와성별별로총대출액합계계산
pivot_result = df.pivot_table(index='지역코드',columns='성별',values='총대출액',aggfunc='sum')
pivot_result

성별                 1         2
지역코드
4100000000  22891981  18339609
4100000001  34197683  17595557
4100000002  13119017  21827691
4100000003  16549091  54654134
4100000004  26831399  56145359
...              ...       ...
4100000587   9050332  19445103
4100000588  47396699  36281031
4100000589  28256320  17797635
4100000590  16813363  23655928
4100000591  20674327  12204772

[592 rows x 2 columns]

In [52]:
pivot_result['차이'] = abs(pivot_result[1] - pivot_result[2])
result = pivot_result['차이'].idxmax()
print(result)

4100000278

In [ ]:
#문제 14-1

In [53]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/crime.csv")

In [54]:
# 1) "발생건수"와 "검거건수"를따로 분리
cond1 = df["구분"] == "발생건수"
cond2 = df["구분"] == "검거건수"
df1 = df[cond1].iloc[:, 2:] # 발생건수만 가져오기
df2 = df[cond2].iloc[:, 2:] # 검거건수만 가져오기

In [55]:
# 2) 검거율계산(검거건수/ 발생건수)
df1 = df1.reset_index(drop=True)
df2 = df2.reset_index(drop=True)
df3 = df2 / df1
df3

,강력범죄,절도범죄,폭력범죄,지능범죄,풍속범죄,특별경제범죄,마약범죄,보건범죄,환경범죄,교통범죄,노동범죄,선거범죄,병역범죄,기타범죄
0,0.625000,0.666667,0.533333,0.692308,0.571429,0.929400,0.583333,0.588235,0.562500,0.611111,0.533333,0.562500,0.571429,0.600000
1,0.666667,0.928385,0.625000,0.733333,0.571429,0.600000,0.588235,0.562500,0.611111,0.631579,0.562500,0.588235,0.533333,0.600000
2,0.588235,0.750000,0.922727,0.733333,0.571429,0.631579,0.555556,0.562500,0.588235,0.611111,0.533333,0.562500,0.571429,0.631579
3,0.600000,0.555556,0.588235,0.687500,0.533333,0.631579,0.928571,0.555556,0.550000,0.631579,0.562500,0.588235,0.533333,0.555556
4,0.931034,0.666667,0.588235,0.687500,0.533333,0.631579,0.555556,0.562500,0.588235,0.611111,0.533333,0.562500,0.571429,0.631579
5,0.600000,0.555556,0.588235,0.687500,0.533333,0.631579,0.555556,0.928571,0.550000,0.631579,0.562500,0.588235,0.533333,0.555556
6,0.600000,0.555556,0.588235,0.908667,0.533333,0.631579,0.555556,0.562500,0.588235,0.611111,0.533333,0.562500,0.571429,0.631579

In [57]:
# 3) 각 연도에서검거율이가장높은범죄유형찾기
listbox = df3.idxmax(axis=1)
listbox

0    특별경제범죄
1      절도범죄
2      폭력범죄
3      마약범죄
4      강력범죄
5      보건범죄
6      지능범죄
dtype: object

In [60]:
# 4) 가장 높은검거율을기록한범죄유형의검거건수 가져오기
result = 0
for index, item in enumerate(listbox):
  result = result + df2.loc[index, item]
print(result)

7799

In [ ]:
#문제 14-2

In [61]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/crime.csv")

In [62]:
# 1. 데이터를길게변환
df_long = pd.melt(df, id_vars=["연도", "구분"], var_name="범죄유형", value_name="건수")
df_long

       연도    구분  범죄유형   건수
0    2014  발생건수  강력범죄  800
1    2014  검거건수  강력범죄  500
2    2015  발생건수  강력범죄  900
3    2015  검거건수  강력범죄  600
4    2016  발생건수  강력범죄  850
..    ...   ...   ...  ...
191  2018  검거건수  기타범죄  600
192  2019  발생건수  기타범죄  900
193  2019  검거건수  기타범죄  500
194  2020  발생건수  기타범죄  950
195  2020  검거건수  기타범죄  600

[196 rows x 4 columns]

In [64]:
df_pivot = df_long.pivot_table(
  index = ['연도','범죄유형'],
  columns='구분',
  values='건수'
).reset_index()
df_pivot

구분    연도    범죄유형    검거건수    발생건수
0   2014    강력범죄   500.0   800.0
1   2014    교통범죄   550.0   900.0
2   2014    기타범죄   600.0  1000.0
3   2014    노동범죄   400.0   750.0
4   2014    마약범죄   350.0   600.0
..   ...     ...     ...     ...
93  2020    지능범죄  1363.0  1500.0
94  2020  특별경제범죄   600.0   950.0
95  2020    폭력범죄   500.0   850.0
96  2020    풍속범죄   400.0   750.0
97  2020    환경범죄   500.0   850.0

[98 rows x 4 columns]

In [65]:
# 3. 검거율 계산
df_pivot["검거율"] = df_pivot["검거건수"] / df_pivot["발생건수"]
df_pivot

구분    연도    범죄유형    검거건수    발생건수       검거율
0   2014    강력범죄   500.0   800.0  0.625000
1   2014    교통범죄   550.0   900.0  0.611111
2   2014    기타범죄   600.0  1000.0  0.600000
3   2014    노동범죄   400.0   750.0  0.533333
4   2014    마약범죄   350.0   600.0  0.583333
..   ...     ...     ...     ...       ...
93  2020    지능범죄  1363.0  1500.0  0.908667
94  2020  특별경제범죄   600.0   950.0  0.631579
95  2020    폭력범죄   500.0   850.0  0.588235
96  2020    풍속범죄   400.0   750.0  0.533333
97  2020    환경범죄   500.0   850.0  0.588235

[98 rows x 5 columns]

In [67]:
# 4. 각 연도별로검거율이가장높은범죄유형찾기
listbox = df_pivot.groupby("연도")["검거율"].idxmax()
listbox

연도
2014    10
2015    22
2016    39
2017    46
2018    56
2019    76
2020    93
Name: 검거율, dtype: int64

In [68]:
max_crime = df_pivot.loc[listbox]
max_crime

구분    연도    범죄유형    검거건수    발생건수       검거율
10  2014  특별경제범죄   961.0  1034.0  0.929400
22  2015    절도범죄   713.0   768.0  0.928385
39  2016    폭력범죄   812.0   880.0  0.922727
46  2017    마약범죄  1300.0  1400.0  0.928571
56  2018    강력범죄  1350.0  1450.0  0.931034
76  2019    보건범죄  1300.0  1400.0  0.928571
93  2020    지능범죄  1363.0  1500.0  0.908667

In [70]:
# 5. 각 연도별최고검거율범죄유형의검거건수를모두합산하기
result = max_crime["검거건수"].sum()
print(result)

7799.0

In [ ]:
#문제 15-1

In [71]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/hr.csv")

In [72]:
# 1) 만족도결측치처리
m = df["만족도"].mean()
df["만족도"] = df["만족도"].fillna(m)

In [75]:
# 2) 근속연수결측치처리(부서와성과등급기준평균값으로채움)
gm = df.groupby(["부서", "성과등급"])["근속연수"].transform("mean")
gm

0      11.517857
1      11.814815
2      10.852459
3      10.622642
4      10.525424
         ...
995    10.166667
996    10.525424
997    11.032258
998    11.032258
999    11.814815
Name: 근속연수, Length: 1000, dtype: float64

In [76]:
#부서와성과등급이같은사람들끼리묶어서근속연수의평균을구하고, 그평균값을원래각행마다대응되게다시채운Series를만든다
gm = gm.astype(int)
df["근속연수"] = df["근속연수"].fillna(gm)

In [78]:
# 3) 연봉 / 근속연수계산후세번째로높은사람의근속연수(A)
df["연봉_근속연수"] = df["연봉"] / df["근속연수"]
df

      사원번호         부서 성과등급         연봉  근속연수  교육참가횟수  만족도       연봉_근속연수
0    E0001  Marketing    B   73200000  14.0       5  6.0  5.228571e+06
1    E0002         IR    A   95100000   3.0       4  9.0  3.170000e+07
2    E0003    Manager    B   44700000   5.0       2  8.0  8.940000e+06
3    E0004         IR    B  122100000  16.0       3  8.0  7.631250e+06
4    E0005         IR    C   66000000  10.0       4  8.0  6.600000e+06
..     ...        ...  ...        ...   ...     ...  ...           ...
995  E0996    Finance    B   90400000  15.0       3  2.0  6.026667e+06
996  E0997         IR    C  147600000  12.0       5  5.0  1.230000e+07
997  E0998      Sales    C   95600000   4.0       4  9.0  2.390000e+07
998  E0999      Sales    C   94400000   8.0       6  1.0  1.180000e+07
999  E1000         IR    A   92400000   9.0       2  5.0  1.026667e+07

[1000 rows x 8 columns]

In [80]:
df_year = df.nlargest(3, '연봉_근속연수')
df_year

      사원번호       부서 성과등급         연봉  근속연수  교육참가횟수       만족도      연봉_근속연수
357  E0358  Finance    B  148100000   1.0       5  8.000000  148100000.0
386  E0387       HR    A  145400000   1.0       1  9.000000  145400000.0
801  E0802       IR    A  144900000   1.0       5  5.017045  144900000.0

In [82]:
A = df_year.iloc[-1]["근속연수"]
A

np.float64(1.0)

In [84]:
# 4) 연봉 / 만족도계산후두번째로높은사람의교육참가횟수(B)
df["연봉_만족도"] = df["연봉"] / df["만족도"]
df_like = df.nlargest(2,'연봉_만족도')
df_like

,사원번호,부서,성과등급,연봉,근속연수,교육참가횟수,만족도,연봉_근속연수,연봉_만족도
490,E0491,Finance,B,149000000,13.0,6,1.0,1.146154e+07,149000000.0
737,E0738,HR,A,146200000,9.0,6,1.0,1.624444e+07,146200000.0

In [85]:
B = df_like.iloc[-1]["교육참가횟수"]
B

np.int64(6)

In [86]:
# 5) 결과 출력
result = A + B
print(result)

7.0

In [ ]:
#문제 15-2

In [87]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/hr.csv")

In [88]:
# 1) 만족도결측치처리
m = df["만족도"].mean()
df["만족도"] = df["만족도"].fillna(m)

In [89]:
# 2) 근속연수결측치처리(부서와성과등급기준평균값으로채움)
gm = df.groupby(["부서", "성과등급"])["근속연수"].transform("mean")
gm = gm.astype(int)
df["근속연수"] = df["근속연수"].fillna(gm)

In [91]:
# 3) 연봉 / 근속연수계산후세번째로높은사람의근속연수(A)
df["연봉_근속연수"] = df["연봉"] / df["근속연수"]
df_year = df.sort_values(by="연봉_근속연수", ascending=False)
A = df_year.iloc[2]["근속연수"]
A

np.float64(1.0)

In [92]:
# 4) 연봉 / 만족도계산후두번째로높은사람의교육참가횟수(B)
df["연봉_만족도"] = df["연봉"] / df["만족도"]
df_like = df.sort_values(by="연봉_만족도", ascending=False)
B = df_like.iloc[1]["교육참가횟수"]
B

np.int64(6)

In [93]:
# 5) 결과 출력
result = A + B
print(result)

7.0